name: Samuran Tech - Sysadmin Blog
title: Samuran Tech - Sysadmin Blog
tagline: Un blog sobre las cosas que he ido aprendiendo en mis pocos años de sysadmin
  y las cosas que iré aprendiendo.
description:
  Un blog sobre las cosas que he ido aprendiendo en mis pocos años de sysadmin
  y las cosas que iré aprendiendo.
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.samurantech.com" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: samurantech #if your site has a twitter account, enter it here
locale: es_ES

# Twitter
twitter:
  username: samurantech
  card: summary

# Author Settings
author: Samuran # add your name
author-img: samuran.jpg # add your photo
about-author: Sysadmin con muchas ganas de aprender y compartir todo ese conocimiento. # add description
social-twitter: samurantech # add your Twitter handle
social-instagram: # add your Facebook handle
social-github: atomarxculo # add your Github handle
social-linkedin: samuel-hernández-gigorro-b65b99173 # add your Linkedin handle
social-email: samuran@samurantech.com # add your Email address
social-slack: samurantech # add your Slack page
social-trello: blog

# Disqus
discus-identifier: samuran-blog # add your discus identifier

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji
  - jekyll-seo-tag

paginate: 8
paginate_path: "/page/:num"